start identifier tests

diff --git a/test/symbol/test-symtab-output b/test/symbol/test-symtab-output
--- a/test/symbol/test-symtab-output
+++ b/test/symbol/test-symtab-output
@@ -41,3 +41,13 @@ then
 else
     echo " FAIL: FUNCTION DEFINITIONS"
 fi
+
+./symbol-main test/symbol/st-in-identifiers test/symbol/st-output
+diff test/symbol/st-exp-identifiers test/symbol/st-output
+
+if [ $? -eq 0 ]
+then
+    echo "PASS: IDENTIFIERS"
+else
+    echo " FAIL: IDENTIFIERS"
+fi
